### PR TITLE
Multiple communities

### PR DESCRIPTION
**Pull request by meskal**
As you probably know, we, the Freifunk Franken community, develops  a new iteration of its firmware, based on your firmware.

However to use the same (or a similar) repository, we need to have some structural changes. 
This pull request aims to adapt your Firmware to support other communities by "just" adding  community-packages.

Please note: *This has not been tested on a router yet*, since I haven't had time yet. Nevertheless I think the idea is clear from the commits and I wanted to give you the chance to discuss these changes as early as possible.

I hope you like the idea of sharing a common base.

Thanks for taking the time to review these changes.
Tobias

PS: These changes aim to not change anything functional within your firmware.

### CODE REVIEW

**Comment by mwarning** [comment]
Hi, we did some minor refactoring so far. We now use /etc/uci-defaults and the freiufnk-bielefeld package was renamed to freifunk.

**Comment by meskal** [comment]
Thanks for the notification!

However the renaming of the freifunk-bielefeld packages brings up the general question if you are interested in supporting "multiple communities"?

If Yes: What would be your direction/preferences to do so?

What is your current development process regarding ffulm and ff-bielefeld?

**Comment by mwarning** [comment]
Support of multiple communities is a necessity. Many small communities in the area can't afford their own infrastructure (yet), but we want also want them to be as independent as possible. Also, we can more easily share resources.
Support means, that communities can setup their own independent map that may only include the nodes of their respective community. Also, the ssid/community setting can be changed and also they can go their own way if they choose to do so.

The firmware between FF-Ulm and Bielefeld are identical execpt for the branding, but the infrastructure is not connected.

My current focus is to improve decentralization and increase scalability.

**Comment by meskal** [comment]
I'm afraid our needs as "another" community are slightly different than those described by you. I should have stated our idea more directly from the beginning.

However, since we couldn't really keep up with your development  and we have a new firmware developer team, we started firmware development from scratch, that is partly(especially when it comes to the repos'  layout and the usage of openwrt) inspired by your repository. I hope that's OK.

I think this means we can close this case.
Thanks

**Comment by mwarning** [comment]
Np, do as you like and have fun. :=)

**Pull request closed without merging**
